Pages/Bookings/Create.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    [Authorize(Roles = "Employee,Guest")]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public CreateModel(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }
        
        [BindProperty(SupportsGet = true)]
        public int RoomIdFromQuery { get; set; }
        public string GuestIdFromSession { get; set; }
        public List<Booking> Bookings { get; set; }
        private readonly IHttpContextAccessor _httpContextAccessor;

        public async Task<IActionResult> OnGetAsync()
        {
            if (!string.IsNullOrEmpty(Request.Query["id"]) && int.TryParse(Request.Query["id"], out int roomIdInt))
            {
                RoomIdFromQuery = roomIdInt;
                Bookings = await _context.Booking.Where(b => b.RoomId == RoomIdFromQuery).ToListAsync();
            }
            else
            {
                ViewData["RoomId"] = new SelectList(_context.Room.ToList(), "Id", "DisplayName");
            }

            if (User.IsInRole("Employee"))
            {
                ViewData["GuestId"] = new SelectList(_context.Users, "Id", "Email");
            } else if (User.IsInRole("Guest"))
            {
                var userId = _httpContextAccessor.HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
                GuestIdFromSession = userId;
            }

            return Page();
        }

        [BindProperty]
        public Booking Booking { get; set; } = default!;
        

        public async Task<IActionResult> OnPostAsync()
        {
            if (Booking.CheckInDate >= Booking.CheckOutDate)
            {
                ModelState.AddModelError("Booking.CheckInDate", "Check-in date must be before check-out date.");
                ModelState.AddModelError("Booking.CheckOutDate", "Check-out date must be after check-in date.");
            }

            var conflicting = _context.Booking.FirstOrDefault(b =>
                b.RoomId == Booking.RoomId && b.CheckInDate < Booking.CheckOutDate &&
                 b.CheckOutDate > Booking.CheckInDate);
            if (conflicting != null)
            {
                ModelState.AddModelError("Booking.CheckInDate", "There is a conflicting booking: " + conflicting.CheckInDate.ToShortDateString() + "-" + conflicting.CheckOutDate.ToShortDateString());
            }
            if (!ModelState.IsValid || _context.Booking == null || Booking == null)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.Write(error.ErrorMessage);
                        
                    }
                    
                }
                ViewData["GuestId"] = new SelectList(_context.Users, "Id", "Email");
                if (!string.IsNullOrEmpty(Request.Query["id"]) && int.TryParse(Request.Query["id"], out int roomIdInt))
                {
                    RoomIdFromQuery = roomIdInt;
                    Bookings = await _context.Booking.Where(b => b.RoomId == RoomIdFromQuery).ToListAsync();
                }
                else
                {
                  ViewData["RoomId"] = new SelectList(_context.Room.ToList(), "Id", "DisplayName");
                }
                return Page();
            }

            _context.Booking.Add(Booking);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Bookings/Delete.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Booking Booking { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .Include(b=> b.Room)
                .Include(b=>b.Guest)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (booking == null)
            {
                return NotFound();
            }

            Booking = booking;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }
            var booking = await _context.Booking.FindAsync(id);

            if (booking != null)
            {
                Booking = booking;
                _context.Booking.Remove(Booking);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Bookings/Details.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

      public Booking Booking { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .Include(b => b.Room)
                .Include(b=>b.Guest)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            Booking = booking;
            return Page();
        }
    }
}

Pages/Bookings/Edit.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    [Authorize(Roles = "Employee")]
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Booking Booking { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking =  await _context.Booking.FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }
            Booking = booking;
           ViewData["GuestId"] = new SelectList(_context.Users, "Id", "Email");
           ViewData["RoomId"] = new SelectList(_context.Room, "Id", "DisplayName");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Booking).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookingExists(Booking.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToPage("./Index");
        }

        private bool BookingExists(int id)
        {
          return (_context.Booking?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Pages/Facilities/Delete.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Facilities
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Facility Facility { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }

            var facility = await _context.Facility.FirstOrDefaultAsync(m => m.Id == id);

            if (facility == null)
            {
                return NotFound();
            }

            Facility = facility;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }
            var facility = await _context.Facility.FindAsync(id);

            if (facility != null)
            {
                Facility = facility;
                _context.Facility.Remove(Facility);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Facilities/Details.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Facilities
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

      public Facility Facility { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }

            var facility = await _context.Facility.FirstOrDefaultAsync(m => m.Id == id);
            if (facility == null)
            {
                return NotFound();
            }

            Facility = facility;
            return Page();
        }
    }
}

Pages/Facilities/Edit.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Facilities
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Facility Facility { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }

            var facility =  await _context.Facility.FirstOrDefaultAsync(m => m.Id == id);
            if (facility == null)
            {
                return NotFound();
            }
            Facility = facility;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Facility).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FacilityExists(Facility.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToPage("./Index");
        }

        private bool FacilityExists(int id)
        {
          return (_context.Facility?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Pages/Rooms/Create.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel.Pages.Rooms
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public CreateModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Room Room { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Room == null || Room == null)
          {
              foreach (var modelState in ModelState.Values)
              {
                  foreach (var error in modelState.Errors)
                  {
                      Console.Write(error.ErrorMessage);
                  }
              }
              return Page();
          }

          _context.Room.Add(Room);
          await _context.SaveChangesAsync();
          
          return RedirectToPage("./Index");
        }
    }
}

Pages/Rooms/Edit.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;

namespace Hotel.Pages.Rooms
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Room Room { get; set; } = default!;
        [BindProperty]
        public List<Facility> Facilities { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room =  await _context.Room.Include(r => r.Facilities).FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }
            Room = room;
            Facilities = await _context.Facility.ToListAsync();
            return Page();
        }

        public async Task<IActionResult> OnPostAssignFacilitiesAsync(int roomId, List<int> facilityIds)
        {
            var room = await _context.Room.Include(r => r.Facilities).FirstOrDefaultAsync(m => m.Id == roomId);
            var facilities = _context.Facility.Where(f => facilityIds.Contains(f.Id));
            if (room != null && facilities != null)
            {
                room.Facilities?.AddRange(facilities);
                await _context.SaveChangesAsync();
            }
            return RedirectToPage("./Edit",new { id = roomId });
        }

        public async Task<IActionResult> OnPostRemoveFacilityAsync(int roomId, int facilityId)
        {
            var room =  await _context.Room.Include(r=>r.Facilities).FirstOrDefaultAsync(m => m.Id == roomId);
            var facility =  await _context.Facility.FirstOrDefaultAsync(m => m.Id == facilityId);
            if (room != null && facility != null)
            {
                room.Facilities?.Remove(facility);
                await _context.SaveChangesAsync();
            }
            return RedirectToPage("./Edit",new { id = roomId });
        }

        public async Task<IActionResult> OnPostUpdateRoomAsync()
        {
            if (!ModelState.IsValid)
            {return Page();}
            _context.Attach(Room).State = EntityState.Modified;
            try
            {await _context.SaveChangesAsync();}
            catch (DbUpdateConcurrencyException)
            {
                if (!RoomExists(Room.Id))
                {return NotFound();}
                throw;
            }

            return RedirectToPage("./Index");
        }

        private bool RoomExists(int id)
        {
          return (_context.Room?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Pages/Rooms/Create.cshtml
@page
@using Hotel.Models
@model Hotel.Pages.Rooms.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <form method="post">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Room.Type" class="control-label"></label>
                <select asp-for="Room.Type" class="form-control">
                    @foreach (var roomType in Enum.GetValues(typeof(RoomType)))
                    {
                        <option value="@roomType">@roomType</option>
                    }
                </select>
                <span asp-validation-for="Room.Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room.Price" class="control-label"></label>
                <input asp-for="Room.Price" class="form-control" />
                <span asp-validation-for="Room.Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

Pages/Rooms/Delete.cshtml
@page
@model Hotel.Pages.Rooms.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Price)
        </dd>
        @if (Model.Room.Facilities != null && Model.Room.Facilities.Any())
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Room.Facilities)
            </dt>
            <dd class="col-sm-10">
                @string.Join(", ", Model.Room.Facilities.Select(r => r.Name))
            </dd>
        }
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Room.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Rooms/Details.cshtml
@page
@model Hotel.Pages.Rooms.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Room.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Room.Price)
        </dd>
        @if (Model.Room.Facilities != null && Model.Room.Facilities.Any())
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Room.Facilities)
            </dt>
            <dd class="col-sm-10">
                @string.Join(", ", Model.Room.Facilities.Select(r => r.Name))
            </dd>
        }
    </dl>
</div>
<div>
     @if (User.IsInRole("Admin"))
     {
         <span><a asp-page="./Edit" asp-route-id="@Model.Room?.Id">Edit</a> | </span>
     }
     <a asp-page="./Index">Back to List</a>
</div>

Pages/Rooms/Edit.cshtml
@page
@model Hotel.Pages.Rooms.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-page-handler="UpdateRoom" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Room.Id" />
            <div class="form-group">
                <label asp-for="Room.Type" class="control-label"></label>
                <select asp-for="Room.Type" class="form-control">
                    <option value="Single">Single</option>
                    <option value="Double">Double</option>
                    <option value="Triple">Triple</option>
                </select>
                <span asp-validation-for="Room.Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Room.Price" class="control-label"></label>
                <input asp-for="Room.Price" class="form-control" />
                <span asp-validation-for="Room.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="mt-3 btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        Room Facilities
        @if (Model.Room.Facilities != null && Model.Room.Facilities.Any())
        {
            @foreach (var facility in Model.Room.Facilities)
            {
                <li>
                    <div class="row">
                        <span class="col mt-2">
                            @facility.Name
                        </span>
                        <span class="col">
                            <form method="post" asp-page-handler="RemoveFacility" asp-route-roomId="@Model.Room.Id" asp-route-facilityId="@facility.Id">
                                <button type="submit" class="btn btn-link text-danger">X</button>
                            </form>
                        </span>
                    </div>
                </li>
            }
        }
        else
        {
            <div>No facilities for this room</div>
        }
    </div>
    <div class="col-md-4">
        Add Facilities
        @if (Model.Facilities.Any(facility => !Model.Room.Facilities!.Contains(facility)))
        {
            <form method="post" asp-page-handler="AssignFacilities" asp-route-roomId="@Model.Room.Id">
                <div class="row">
                    <span class="col">
                        <select multiple name="facilityIds" class="form-control">
                            @foreach (var facility in Model.Facilities)
                            {
                                @if (Model.Room.Facilities != null && Model.Room.Facilities.All(r => r.Id != facility.Id))
                                {
                                    <option value="@facility.Id">@facility.Name</option>
                                }
                            }
                        </select>
                    </span>
                    <span class="col">
                        <button type="submit" class="btn btn-link">Assign</button>
                    </span>
                </div>
            </form>
        }
        else
        {
            <div>No more available facilities</div>
        }
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Rooms/Index.cshtml
@page "/"
@model Hotel.Pages.Rooms.IndexModel

@{
    ViewData["Title"] = "Rooms";
}

<h1>Rooms</h1>

@if (User.IsInRole("Admin"))
{
    <p><a asp-page="Create">Create New</a></p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rooms[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rooms[0].Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rooms[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rooms[0].Facilities)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Rooms) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @if (item.Facilities != null)
                    {
                        if (item.Facilities != null && item.Facilities.Any())
                        {
                            <ul class="list-unstyled">
                                @foreach (var facility in item.Facilities)
                                {
                                    <li>@facility.Name</li>
                                }
                            </ul>
                        }
                    }
                    else
                    {
                        <span>No facilities</span>
                    }


                </td>
                <td>
                    @if (User.IsInRole("Admin"))
                    {
                        <div>
                            <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a> |
                        </div>
                    }
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="/Bookings/Create" asp-route-id="@item.Id">Book</a>
                </td>
            </tr>
        }
    </tbody>
</table>