Pages/Bookings/Create.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    [Authorize(Roles = "Employee,Guest")]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public CreateModel(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }
        
        [BindProperty(SupportsGet = true)]
        public int RoomIdFromQuery { get; set; }
        public string GuestIdFromSession { get; set; }
        public List<Booking> Bookings { get; set; }
        private readonly IHttpContextAccessor _httpContextAccessor;

        public async Task<IActionResult> OnGetAsync()
        {
            if (!string.IsNullOrEmpty(Request.Query["id"]) && int.TryParse(Request.Query["id"], out int roomIdInt))
            {
                RoomIdFromQuery = roomIdInt;
                Bookings = await _context.Booking.Where(b => b.RoomId == RoomIdFromQuery).ToListAsync();
            }
            else
            {
                ViewData["RoomId"] = new SelectList(_context.Room.ToList(), "Id", "DisplayName");
            }

            if (User.IsInRole("Employee"))
            {
                ViewData["GuestId"] = new SelectList(_context.Users, "Id", "Email");
            } else if (User.IsInRole("Guest"))
            {
                var userId = _httpContextAccessor.HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
                GuestIdFromSession = userId;
            }

            return Page();
        }

        [BindProperty]
        public Booking Booking { get; set; } = default!;
        

        public async Task<IActionResult> OnPostAsync()
        {
            if (Booking.CheckInDate >= Booking.CheckOutDate)
            {
                ModelState.AddModelError("Booking.CheckInDate", "Check-in date must be before check-out date.");
                ModelState.AddModelError("Booking.CheckOutDate", "Check-out date must be after check-in date.");
            }

            var conflicting = _context.Booking.FirstOrDefault(b =>
                b.RoomId == Booking.RoomId && b.CheckInDate < Booking.CheckOutDate &&
                 b.CheckOutDate > Booking.CheckInDate);
            if (conflicting != null)
            {
                ModelState.AddModelError("Booking.CheckInDate", "There is a conflicting booking: " + conflicting.CheckInDate.ToShortDateString() + "-" + conflicting.CheckOutDate.ToShortDateString());
            }
            if (!ModelState.IsValid || _context.Booking == null || Booking == null)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Console.Write(error.ErrorMessage);
                        
                    }
                    
                }
                ViewData["GuestId"] = new SelectList(_context.Users, "Id", "Email");
                if (!string.IsNullOrEmpty(Request.Query["id"]) && int.TryParse(Request.Query["id"], out int roomIdInt))
                {
                    RoomIdFromQuery = roomIdInt;
                    Bookings = await _context.Booking.Where(b => b.RoomId == RoomIdFromQuery).ToListAsync();
                }
                else
                {
                  ViewData["RoomId"] = new SelectList(_context.Room.ToList(), "Id", "DisplayName");
                }
                return Page();
            }

            _context.Booking.Add(Booking);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Bookings/Delete.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Booking Booking { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .Include(b=> b.Room)
                .Include(b=>b.Guest)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (booking == null)
            {
                return NotFound();
            }

            Booking = booking;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }
            var booking = await _context.Booking.FindAsync(id);

            if (booking != null)
            {
                Booking = booking;
                _context.Booking.Remove(Booking);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Bookings/Details.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

      public Booking Booking { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .Include(b => b.Room)
                .Include(b=>b.Guest)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            Booking = booking;
            return Page();
        }
    }
}

Pages/Bookings/Edit.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    [Authorize(Roles = "Employee")]
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Booking Booking { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Booking == null)
            {
                return NotFound();
            }

            var booking =  await _context.Booking.FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }
            Booking = booking;
           ViewData["GuestId"] = new SelectList(_context.Users, "Id", "Email");
           ViewData["RoomId"] = new SelectList(_context.Room, "Id", "DisplayName");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Booking).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookingExists(Booking.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToPage("./Index");
        }

        private bool BookingExists(int id)
        {
          return (_context.Booking?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Pages/Bookings/Index.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Bookings
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IndexModel(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        public IList<Booking> Booking { get;set; } = default!;
        private readonly IHttpContextAccessor _httpContextAccessor;
        
        public async Task OnGetAsync()
        {
            if (_context.Booking != null)
            {
                if (User.IsInRole("Guest"))
                {
                    var userId = _httpContextAccessor.HttpContext.User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
                    Booking = await _context.Booking.Where(b=>b.GuestId == userId)
                    .Include(b => b.Guest)
                    .Include(b => b.Room).ToListAsync();                    
                }
                else
                {
                    Booking = await _context.Booking
                    .Include(b => b.Guest)
                    .Include(b => b.Room).ToListAsync();
                }
            }
        }
        
        public async Task<IActionResult> OnPostApproveAsync(int id)
        {
            var booking= await _context.Booking.FindAsync(id);
            if (booking == null) return RedirectToPage("./Index");
            booking.State = BookingState.Confirmed;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Index");
        }
        
        public async Task<IActionResult> OnPostDeclineAsync(int id)
        {
            var booking= await _context.Booking.FindAsync(id);
            if (booking == null) return RedirectToPage("./Index");
            booking.State = BookingState.Declined;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Index");
        }
    }
}

Pages/Facilities/Delete.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Facilities
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Facility Facility { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }

            var facility = await _context.Facility.FirstOrDefaultAsync(m => m.Id == id);

            if (facility == null)
            {
                return NotFound();
            }

            Facility = facility;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }
            var facility = await _context.Facility.FindAsync(id);

            if (facility != null)
            {
                Facility = facility;
                _context.Facility.Remove(Facility);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Facilities/Details.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Facilities
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

      public Facility Facility { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }

            var facility = await _context.Facility.FirstOrDefaultAsync(m => m.Id == id);
            if (facility == null)
            {
                return NotFound();
            }

            Facility = facility;
            return Page();
        }
    }
}

Pages/Facilities/Edit.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Facilities
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Facility Facility { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Facility == null)
            {
                return NotFound();
            }

            var facility =  await _context.Facility.FirstOrDefaultAsync(m => m.Id == id);
            if (facility == null)
            {
                return NotFound();
            }
            Facility = facility;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Facility).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FacilityExists(Facility.Id))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToPage("./Index");
        }

        private bool FacilityExists(int id)
        {
          return (_context.Facility?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Pages/Rooms/Create.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel.Pages.Rooms
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public CreateModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Room Room { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Room == null || Room == null)
          {
              foreach (var modelState in ModelState.Values)
              {
                  foreach (var error in modelState.Errors)
                  {
                      Console.Write(error.ErrorMessage);
                  }
              }
              return Page();
          }

          _context.Room.Add(Room);
          await _context.SaveChangesAsync();
          
          return RedirectToPage("./Index");
        }
    }
}

Pages/Rooms/Details.cshtml.cs
using Hotel.Data;
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Hotel.Pages.Rooms
{
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

      public Room Room { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Room == null)
            {
                return NotFound();
            }

            var room = await _context.Room.Include(r => r.Facilities).FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            Room = room;
            return Page();
        }
    }
}

Pages/Bookings/Create.cshtml
@page
@using Hotel.Models
@model Hotel.Pages.Bookings.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h4>Book room @if(Model.RoomIdFromQuery != 0){<span>#@Model.RoomIdFromQuery</span>}
</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (User.IsInRole("Employee"))
            {
                <div class="form-group">
                    <label asp-for="Booking.GuestId" class="control-label"></label>
                    <select asp-for="Booking.GuestId" class="form-control" asp-items="ViewBag.GuestId"></select>
                </div>
            }
            else
            {
                <div class="form-group">
                    <input type="hidden" asp-for="Booking.GuestId" value="@Model.GuestIdFromSession"/>
                </div>
            }
            @if(Model.RoomIdFromQuery != 0){
                <div class="form-group">
                    <input type="hidden" asp-for="Booking.RoomId" value="@Model.RoomIdFromQuery"/>
                </div>
            }
            else
            {
                <div class="form-group">
                    <label asp-for="Booking.RoomId" class="control-label"></label>
                    <select asp-for="Booking.RoomId" class ="form-control" asp-items="ViewBag.RoomId"></select>
                </div>
            }
            <div class="form-group">
                <label asp-for="Booking.CheckInDate" class="control-label"></label>
                <input asp-for="Booking.CheckInDate" class="form-control" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
                <span asp-validation-for="Booking.CheckInDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Booking.CheckOutDate" class="control-label"></label>
                <input asp-for="Booking.CheckOutDate" value="@DateTime.Today.AddDays(3).ToString("yyyy-MM-dd")" class="form-control" />
                <span asp-validation-for="Booking.CheckOutDate" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Booking.State" value="@BookingState.Pending"/>
            
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
    @if (Model.Bookings != null && Model.Bookings.Any())
    {
        <div class="col-md-4">
            Existing Bookings for room #@Model.RoomIdFromQuery
            <ul>
                @foreach (var booking in Model.Bookings)
                {
                    <li>@booking.CheckInDate.ToShortDateString() - @booking.CheckOutDate.ToShortDateString()</li>
                }
            </ul>
        </div>
    }
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

Pages/Bookings/Delete.cshtml
@page
@model Hotel.Pages.Bookings.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.CheckInDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.CheckInDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.CheckOutDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.CheckOutDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Reason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Reason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Guest)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Guest.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Room)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Room.DisplayName)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Booking.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Bookings/Details.cshtml
@page
@model Hotel.Pages.Bookings.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.CheckInDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.CheckInDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.CheckOutDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.CheckOutDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Reason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Reason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Guest)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Guest.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Booking.Room)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Booking.Room.DisplayName)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Index">Back to List</a>
    @if (User.IsInRole("Employee"))
    {
        <div> | <a asp-page="./Edit" asp-route-id="@Model.Booking?.Id">Edit</a></div>
    }
</div>

Pages/Bookings/Edit.cshtml
@page
@using Hotel.Models
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Hotel.Pages.Bookings.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Booking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Booking.Id" />
            <div class="form-group">
                <label asp-for="Booking.GuestId" class="control-label"></label>
                <select asp-for="Booking.GuestId" class="form-control" asp-items="ViewBag.GuestId"></select>
                <span asp-validation-for="Booking.GuestId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Booking.RoomId" class="control-label"></label>
                <select asp-for="Booking.RoomId" class="form-control" asp-items="ViewBag.RoomId"></select>
                <span asp-validation-for="Booking.RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Booking.CheckInDate" class="control-label"></label>
                <input asp-for="Booking.CheckInDate" class="form-control" />
                <span asp-validation-for="Booking.CheckInDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Booking.CheckOutDate" class="control-label"></label>
                <input asp-for="Booking.CheckOutDate" class="form-control" />
                <span asp-validation-for="Booking.CheckOutDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Booking.State" class="control-label"></label>
                <select asp-for="Booking.State" class="form-control">
                    @foreach (var state in Enum.GetValues(typeof(BookingState)))
                    {
                        <option value="@state">@state</option>
                    }
                    </select>
                <span asp-validation-for="Booking.State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Bookings/Index.cshtml
@page
@using Hotel.Models
@model Hotel.Pages.Bookings.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].CheckInDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].CheckOutDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].Guest)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Booking[0].Room)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Booking) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CheckInDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckOutDate)
            </td>
            <td class="@(item.State switch
                       {
                           BookingState.Declined or BookingState.Canceled => "text-danger",
                           _ => "text-success"
                       })">
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Guest.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.DisplayName)
            </td>
            <td>
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a>
                @if (User.IsInRole("Employee") && item.State == BookingState.Pending)
                {
                    <br/>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a>
                }
                @if (User.IsInRole("Employee") && item.State == BookingState.Pending)
                {
                   <form method="post" asp-page-handler="Approve" asp-route-id="@item.Id">
                       <button type="submit" class="p-0 btn btn-link text-success">Approve👍</button>
                   </form>
                   <form method="post" asp-page-handler="Decline" asp-route-id="@item.Id">
                       <button type="submit" class="p-0 btn btn-link text-danger">Decline 👎</button>
                   </form>
                }
            </td>
        </tr>
}
    </tbody>
</table>